### ISSUE TITLE
Problem using in Flask running with gunicorn

### ISSUE THREAD

**Issue by wong2** [coleifer/vedis-python#10]
I have a Flask app using vedis-python, I use it like this:

    db = Vedis('store.db')
    ...
    with db.transaction():
        db.hset(hashname, k, v)

I'm running it with gunicorn, if the worker number is larger than 1, I got this error:

> IOError: Another process or thread hold the requested lock
> Another process or thread hold the requested lock
> Another process or thread hold the requested lock
> Cannot obtain an Exclusive lock on the target database

if I set the worker num to 1, it works normally.

**Comment by coleifer** [comment]
Vedis is an *embedded* database, and the db files apparently do not support access from multiple processes.
