### ISSUE TITLE
Unable to import vedis after installing

### ISSUE THREAD

**Issue by voonfoo98** [coleifer/vedis-python#15]
![1](https://user-images.githubusercontent.com/32300067/50372188-8d31d580-0604-11e9-9be7-b60835deb7fc.JPG)

pylint gives me this error when i try to import vedis - **"No name 'Vedis' in module vedis"**
I have successfully installed everything but it gives me this error when im trying to import it.

**Comment by karipnail** [comment]
how you fix it?

**Comment by dikdack** [comment]
hooooooooooow???

**Comment by coleifer** [comment]
The guy who asked literally pasted a screenshot of his code. I wouldn't expect much...
