### ISSUE TITLE
Get all keys

### ISSUE THREAD

**Issue by sigaev-pro** [coleifer/vedis-python#17]
Hello, friends

Please tell me, maybe I’m blind, but I don’t see a method for getting all the keys. Is there any analogue of the keys command in redis?

**Comment by coleifer** [comment]
There are no iterators, nor is there a keys command. You can verify by looking at the c API doc: http://vedis.symisc.net/c_api.html or the header:

https://github.com/coleifer/vedis-python/blob/master/src/vedis.h

There are provisions for cursors/iterators in the library code, but it's marked private.

**Comment by ohld** [comment]
So there is no way to get all saved in vedis db data? I've saved a lot of values but how can I retrieve them if I don't know the keys?

**Comment by coleifer** [comment]
You can mark it with a thumbs-down all you want (??), but it doesn't change the fact that the underlying library doesn't support this. As I said in my earlier comment, just review the c api doc or the header.

**Comment by ohld** [comment]
I found a solution: I just store all keys in Set.

**Comment by coleifer** [comment]
That is a terrible solution. Please nobody do that.
