### ISSUE TITLE
Error when i install vedis with pip

### ISSUE THREAD

**Issue by Antony201** [coleifer/vedis-python#18]
when i type "pip install vedis" i get error : 
Command "/home/anton/PycharmProjects/Family_bot/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gq8y8ezf/vedis/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bww0tt78/install-record.txt --single-version-externally-managed --compile --install-headers /home/anton/PycharmProjects/Family_bot/venv/include/site/python3.6/vedis" failed with error code 1 in /tmp/pip-install-gq8y8ezf/vedis/

**Comment by coleifer** [comment]
Please format code or tracebacks using the appropriate markup. When someone can't take the time to do this simple thing, I can't take the time to try and read their issue.
