### ISSUE TITLE
error while opening the target database file: database.vdb

### ISSUE THREAD

**Issue by GraphGrailAi** [coleifer/vedis-python#21]
Hi, i am trying get value from Vedis, the following code works:

```
def get_current_state(user_id):
    with Vedis(db_file) as db:
        try:
            return db[user_id].decode()  # 0.7.1, 
        except KeyError:  
            return States.S_START.value  
```

But SOMETIMES i got this error (below) that result in my code stuck with no value returned. As i understand Python cannot open database from filesystem but why? I would like to say that this error occurs sometimes, after several users use our service, if i restart Python process all works again some time, but the suddenly broken again

```

 File "bot2.py", line 578, in <lambda>
    @bot.message_handler(func=lambda message: get_current_state(message.from_user.id) == States.S_ENTER_TYPE.value)
  File "bot2.py", line 117, in get_current_state
    return db[user_id].decode()  # 0.7.1, 
  File "vedis.pyx", line 390, in vedis.Vedis.__getitem__
  File "vedis.pyx", line 324, in vedis.Vedis.fetch
  File "vedis.pyx", line 425, in vedis.Vedis.check_call
OSError: b'IO error while opening the target database file: /var/bot/database.vdb\n'
```

**Comment by coleifer** [comment]
The error is reported by Vedis.

https://github.com/symisc/vedis/blob/master/vedis.c#L4850-L4867

Consult the vedis docs to troubleshoot.

**Comment by yeralexey** [comment]
> Hi, i am trying get value from Vedis, the following code works:
> 
> ```
> def get_current_state(user_id):
>     with Vedis(db_file) as db:
>         try:
>             return db[user_id].decode()  # 0.7.1, 
>         except KeyError:  
>             return States.S_START.value  
> ```
> 
> But SOMETIMES i got this error (below) that result in my code stuck with no value returned. As i understand Python cannot open database from filesystem but why? I would like to say that this error occurs sometimes, after several users use our service, if i restart Python process all works again some time, but the suddenly broken again
> 
> ```
> 
>  File "bot2.py", line 578, in <lambda>
>     @bot.message_handler(func=lambda message: get_current_state(message.from_user.id) == States.S_ENTER_TYPE.value)
>   File "bot2.py", line 117, in get_current_state
>     return db[user_id].decode()  # 0.7.1, 
>   File "vedis.pyx", line 390, in vedis.Vedis.__getitem__
>   File "vedis.pyx", line 324, in vedis.Vedis.fetch
>   File "vedis.pyx", line 425, in vedis.Vedis.check_call
> OSError: b'IO error while opening the target database file: /var/bot/database.vdb\n'
> ```

so did u manage to solve it? i am not good enough in pytyhon yet, but checked the docks and didnt find a troubleshoot for this...

**Comment by coleifer** [comment]
Just a heads-up, I don't think Vedis is really maintained. I'd strongly recommend porting your code over to Sqlite or something similar, if possible.

**Comment by yeralexey** [comment]
> Just a heads-up, I don't think Vedis is really maintained. I'd strongly recommend porting your code over to Sqlite or something similar, if possible.

 Thanks! Can you give a hint on smth similar?
 
 i tryed to improve a code with glopal flag check, with hope that it will work... But still the same.
 ```
 def get_user_attribute(user_id, attribute):
    """
        Returns value of some users attribute by users id and name of the attribute
    :param user_id: id of the user
    :param attribute: name of attribute
    :return: user attribute value if success, "None" if KeyError and some shit if shit happened...
    """
    global welcome
    while welcome is False:
        continue
    welcome = False
    with Vedis(config.main_db_file) as db:
        try:
            result = db[f'{user_id}{attribute}'].decode()
        except KeyError:
            result = None
        except:
            result = "database fail"
            save_traceback(str(traceback.format_exc()))
    welcome = True
    return result```

@coleifer

**Comment by yeralexey** [comment]
so, this is the only page is being find by tag of such vedis troubleshooting, so i will write here.
after few checks i completed i can say that vedis gives this fail after being called 1010 times, and thoi mistake repeats on vps servers and doesnt on my home computer, so i guess it is some autor made limitations.

----------------------------------
2022-12-21 12:16:48.042288
Traceback (most recent call last):
  File "/home/vedischeck/dbworker.py", line 30, in write_user_attribute
    db[f'{user_id}{attribute}'] = data
  File "vedis.pyx", line 383, in vedis.Vedis.__setitem__
  File "vedis.pyx", line 311, in vedis.Vedis.store
  File "vedis.pyx", line 425, in vedis.Vedis.check_call
OSError: b'IO error while opening journal file: /home/vedischeck/main.vdb_vedis_journal\n'

----------------------------------
2022-12-21 12:16:48.061854
Traceback (most recent call last):
  File "/home/vedischeck/dbworker.py", line 30, in write_user_a

    db[f'{user_id}{attribute}'] = data
  File "vedis.pyx", line 383, in vedis.Vedis.__setitem__
  File "vedis.pyx", line 311, in vedis.Vedis.store
  File "vedis.pyx", line 425, in vedis.Vedis.check_call
OSError: b'IO error while opening the target database file: /home/vedischeck/main.vdb\n'

**Comment by coleifer** [comment]
I'm sorry to hear you're having trouble. As I said earlier, I believe vedis has been abandoned and is not suitable for use. I strongly recommend porting your code to a different database.
