### ISSUE TITLE
Missing key return None instead of raising KeyError

### ISSUE THREAD

**Issue by aaiyer** [coleifer/vedis-python#4]
```
from vedis import Vedis
db = Vedis()
db['k1'] = 'v1'
db.append('k1', 'more data')
del db['k1']
try:
	print(db['k1'])
except Exception as e:
	print(str(e))
```

The above code prints None

**Comment by coleifer** [comment]
That is the intended behavior for `Vedis`. It uses the `GET` vedis command.

If you want to interact with the key/value store, you can use `kv_fetch`, `kv_store`, etc, which *will* raise `KeyError`.

**Comment by aaiyer** [comment]
Need to change documentation -- http://vedis-python.readthedocs.org/en/latest/quickstart.html

Check the first code example you have there.
