### ISSUE TITLE
Vedic error with strings vs bytes

### ISSUE THREAD

**Issue by davidmankin** [coleifer/vedis-python#5]
I can't use the Vedis library in the way described in the example because it rejects the initializer call whether I use bytes or strings.  Same problem in python 2.7.   All on OS X Yosemite.

     $ python
     Python 3.4.3 (default, Jul 14 2015, 13:37:58)
     [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
     Type "help", "copyright", "credits" or "license" for more information.
     >>> from vedis import Vedis
     >>> db = Vedis(':mem:')
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "vedis.pyx", line 231, in vedis.Vedis.__init__ (vedis.c:2250)
       File "vedis.pyx", line 242, in vedis.Vedis.open (vedis.c:2365)
     TypeError: expected bytes, str found
     >>> db = Vedis(b':mem:')
     Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
       File "vedis.pyx", line 227, in vedis.Vedis.__init__ (vedis.c:2202)
     TypeError: Expected str, got bytes
     
     $ venv/bin/pip freeze
     vedis==0.3.1

**Comment by coleifer** [comment]
Hmm, in Cython it's declared as a `const char *`. The conversion should just work, maybe a python 3 issue?

**Comment by davidmankin** [comment]
I tried with both python 3.4 and python 2.7.  I had the same problem with the unqlite python library too. Maybe i's related to Mac OS?

**Comment by coleifer** [comment]
Should be fixed as of 0.4.0.
