### ISSUE TITLE
How to delete hashes and lists?

### ISSUE THREAD

**Issue by Kondra007** [coleifer/vedis-python#9]
Is it possible to do this? From what I see in documentation, only simple key-value pairs can be deleted using either `Vedis.delete()` or `del`

**Comment by coleifer** [comment]
Did you try to use delete to remove a hash or list?

**Comment by Kondra007** [comment]
I've tried this:
```python
h = v.Hash("my_key")
h["k1"] = "v1"
v.delete("my_key")
print(v.Hash("my_key"))
```

`v.delete` produces `KeyError`
However, on key-value pairs `delete` works fine for me.

**Comment by coleifer** [comment]
As far as I can tell, unfortunately, Vedis does not support a single command to delete a hash.

**Comment by coleifer** [comment]
I would avoid Vedis and try something like [rlite](https://github.com/seppo0010/rlite), which has Python bindings.

**Comment by Kondra007** [comment]
Thank you very much! Not many developers these days try to help people by telling about alternatives (instead of just closing).
That's really nice.
